// Generated by CoffeeScript 1.9.1

/*:
 * @plugindesc Skip Title Plugin
 * @author Dan Yamamoto
 * @license MIT
 *
 */

(function() {
  var load_game;

  load_game = function() {
    if (DataManager.isAnySavefileExists()) {
      return DataManager.loadGame(1);
    } else {
      return DataManager.setupNewGame();
    }
  };

  Scene_Title.prototype.create = function() {
    return Scene_Base.prototype.create.call(this);
  };

  Scene_Title.prototype.start = function() {
    Scene_Base.prototype.start.call(this);
    load_game();
    SceneManager.clearStack();
    return SceneManager.goto(Scene_Map);
  };

  Scene_Title.prototype.update = function() {
    return Scene_Base.prototype.update.call(this);
  };

  Scene_Title.prototype.isBusy = function() {
    return Scene_Base.prototype.isBusy.call(this);
  };

}).call(this);
