// Generated by CoffeeScript 1.9.1
(function() {
  var CordovaUnityAds, gameId, isTest, rewardedVideoAdPlacementId, setup, videoAdPlacementId;

  gameId = '42517';

  videoAdPlacementId = 'defaultZone';

  rewardedVideoAdPlacementId = 'rewardedVideoZone';

  isTest = true;

  if (window.unityads == null) {
    window.unityads = {
      showVideoAd: function() {},
      showRewardedVideoAd: function() {},
      loadedVideoAd: function() {
        return false;
      },
      loadedRewardedVideoAd: function() {
        return false;
      },
      isShowingVideoAd: function() {
        return false;
      },
      isShowingRewardedVideoAd: function() {
        return false;
      }
    };
  }

  CordovaUnityAds = (function() {
    function CordovaUnityAds() {
      this.status = null;
      this.has_reward = false;
    }

    CordovaUnityAds.prototype.showVideoAd = function() {
      if (this.loadedVideoAd()) {
        return window.unityads.showVideoAd();
      } else {
        return console.log('not loadedVideoAd');
      }
    };

    CordovaUnityAds.prototype.showRewardedVideoAd = function() {
      if (this.loadedRewardedVideoAd()) {
        window.unityads.showRewardedVideoAd();
        return this.status = 'isReady';
      } else {
        return console.log('not loadedRewardedVideoAd');
      }
    };

    CordovaUnityAds.prototype.loadedVideoAd = function() {
      return window.unityads.loadedVideoAd();
    };

    CordovaUnityAds.prototype.loadedRewardedVideoAd = function() {
      return window.unityads.loadedRewardedVideoAd();
    };

    CordovaUnityAds.prototype.isShowingVideoAd = function() {
      return window.unityads.isShowingVideoAd();
    };

    CordovaUnityAds.prototype.isShowingRewardedVideoAd = function() {
      return window.unityads.isShowingRewardedVideoAd();
    };

    CordovaUnityAds.prototype.isShowing = function() {
      return this.status !== null;
    };

    CordovaUnityAds.prototype.hasReward = function() {
      return this.has_reward;
    };

    CordovaUnityAds.prototype.clearReward = function() {
      return this.has_reward = false;
    };

    return CordovaUnityAds;

  })();

  window.unityAds = new CordovaUnityAds();

  setup = function() {
    window.unityads.setUp(gameId, videoAdPlacementId, rewardedVideoAdPlacementId, isTest);
    window.unityads.onVideoAdLoaded = function() {
      if (isTest) {
        return console.log('onVideoAdLoaded');
      }
    };
    window.unityads.onVideoAdShown = function() {
      if (isTest) {
        return console.log('onVideoAdShown');
      }
    };
    window.unityads.onVideoAdHidden = function() {
      if (isTest) {
        return console.log('onVideoAdHidden');
      }
    };
    window.unityads.onRewardedVideoAdLoaded = function() {
      if (isTest) {
        return console.log('onRewardedVideoAdLoaded');
      }
    };
    window.unityads.onRewardedVideoAdShown = function() {
      if (isTest) {
        console.log('onRewardedVideoAdShown');
      }
      return window.unityAds.status = 'isShowing';
    };
    window.unityads.onRewardedVideoAdHidden = function() {
      if (isTest) {
        console.log('onRewardedVideoAdHidden');
      }
      return window.unityAds.status = null;
    };
    return window.unityads.onRewardedVideoAdCompleted = function() {
      if (isTest) {
        console.log('onRewardedVideoAdCompleted');
      }
      return this.has_reward = true;
    };
  };

  document.addEventListener("deviceready", setup, false);

}).call(this);
